(function (g) { g.REALTOR_DESCRIPTION_IDS = [
  "nb-sport-city",
  "nb-stay-rent",
  "new-bilding-one",
  "nb-ramada-one-development",
  "apt-orbi-beach-tower-2201",
  "apt-orbi-beach-tower-2801",
  "apt-orbi-beach-tower-3202",
  "apt-orbi-beach-tower-2902",
  "apt-orbi-beach-tower-2912",
  "apt-orbi-city-d1-1p1",
  "apt-avenue-by-orbi-studio",
  "apt-raduga-elt-studio",
  "apt-alliance-privilege-studio",
  "apt-marina-club-1p1",
  "apt-batumi-view-studio",
  "apt-steps-batumi-studio",
  "apt-steps-batumi-studio-11",
  "apt-steps-batumi-2p1",
  "apt-tropical-garden-studio",
  "house-villa-park-next",
  "house-polo-villas-parklane",
  "house-adlia-townhouse-222",
  "house-kobuleti-sea"
]; })(typeof window !== "undefined" ? window : globalThis);
